#!/bin/bash

daynum=$(printf %02d $1)
mkdir Day_$daynum

if [ -f input.txt ]; then
	mv input.txt Day_$daynum/input.txt
fi

for i in "1" "2"
do
echo 'result = 0

with open("input.txt", "r") as input:
    for line in input:
        line = line.strip()

with open("output'$i'.txt", "w") as output:
    output.write(str(result))
    print(str(result))
' > ./Day_$daynum/part$i.py
done

touch ./Day_$daynum/input.txt